INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (1, 1000.00, 1);
INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (2, 100.00, 1);
INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (3, 10.00, 2);
INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (4, 100.00, 3);
INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (5, 100.00, 1);
INSERT INTO REIMBURSEMENT (REIMBURSEMENT_ID, AMOUNT, EMPLOYEE_ID) VALUES (6, 10.00, 2);

COMMIT;